lab2:
	@echo "Running program Ex1.5"
	@g++ Execrise1_5.cpp -o Exercise1_5
	@./Exercise1_5
	@echo "Running program Ex1.11 (for statement)"
	@g++ Exercise1_11.cpp -o Exercise1_11
	@./Exercise1_11
	@echo "Running program Ex1.11 (while statement)"
	@g++ Exercise1_112.cpp -o Exercise1_112
	@./Exercise1_112